### ISSUE TITLE
PyGIDeprecationWarnings

### ISSUE THREAD

**Issue by FriedrichFroebel** [linuxmint/mintsources#104] opened 2018-01-28 13:34 UTC
Running `mintsources` from the terminal raises some warnings:

```
/usr/lib/linuxmint/mintSources/mintSources.py:380: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  Gtk.CheckButton.__init__(self, self.component.description)
/usr/lib/linuxmint/mintSources/mintSources.py:277: PyGIDeprecationWarning: GObject.markup_escape_text is deprecated; use GLib.markup_escape_text instead
  return "<b>%s</b>\n<small><i>%s</i></small>" % (GObject.markup_escape_text(self.uid), GObject.markup_escape_text(self.pub))
/usr/lib/linuxmint/mintSources/mintSources.py:1328: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "parent, flags, message_type, buttons, message_format" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  message)
/usr/lib/linuxmint/mintSources/mintSources.py:1328: PyGTKDeprecationWarning: The keyword(s) "message_format" have been deprecated in favor of "text" respectively. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  message)
/usr/lib/linuxmint/mintSources/mintSources.py:1328: PyGTKDeprecationWarning: The "flags" argument for dialog construction is deprecated. Please use initializer keywords: modal=True and/or destroy_with_parent=True. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  message)
/usr/local/lib/python2.7/dist-packages/gi/overrides/Gtk.py:542: PyGTKDeprecationWarning: The keyword(s) "parent" have been deprecated in favor of "transient_for" respectively. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  self._init(*args, **new_kwargs)
```

**Comment by xenopeek** [comment] 2018-01-29 12:42
I tested this on Linux Mint 18.3 with mintsources version 1.7.2 and cannot reproduce.

Are you using an older Linux Mint version or an older mintsources version? If you're unsure sure run `inxi -S` on the terminal to find your Linux Mint version and `apt version mintsources` to find your mintsources version.

If those versions match yours, check your Python versions with `python2 --version` and `python3 --version` which should respond Python 2.7.12 and Python 3.5.2.

If all versions are matching and correct, please try to find out the exact action you take that causes these messages to appear.

**Comment by FriedrichFroebel** [comment] 2018-01-29 15:41
All my versions are the same as yours.

Reproduce the first two warnings: Type `mintsources`, hit enter, enter your password and they appear.

Reproduce the other warnings: Switch to "Additional package sources", click on "New package ...".

The only difference may be that I am using a newer PyGObject version than you. In my case it is PyGObject 3.27.1 from PIP (for both Python versions).

**Comment by xenopeek** [comment] 2018-06-04 06:54
Fixed in Linux Mint 19 release.

**Closed by xenopeek** 2018-06-04 06:54 UTC
Labels: Reviewed
