### ISSUE TITLE
add-apt-repository fails under sudo

### ISSUE THREAD

**Issue by mbligh** [linuxmint/mintsources#180] opened 2019-10-11 19:05 UTC
On mint 19.2, the following command fails under sudo, but works fine in a root shell
add-apt-repository  -y ppa:jon-hedgerows/get-iplayer
I am not sure why it only happens under sudo, but from what I can make of the Python it seems like it's grabbing an unknown string from a 3rd party, then crashing if it can't encode it as ASCII, which doesn't seem great. I used the following change to /usr/lib/linuxmint/mintSources/mintSources.py

```
--- /usr/lib/linuxmint/mintSources/mintSources.py.old   2019-10-11 14:50:57.727625216 -0400
+++ /usr/lib/linuxmint/mintSources/mintSources.py       2019-10-11 14:55:59.405370693 -0400
@@ -154,7 +154,7 @@
 
         print(_("You are about to add the following PPA:"))
         if ppa_info["description"] is not None:
-            print(" %s" % (ppa_info["description"]))
+            print(" %s" % (ppa_info["description"].encode("utf8", "ignore")))
         print(_(" More info: %s") % str(ppa_info["web_link"]))
 
         if sys.stdin.isatty():
```

but there may well be a better way. The error I get is:

```
$ sudo add-apt-repository  -y ppa:jon-hedgerows/get-iplayer
You are about to add the following PPA:
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 1887, in <module>
    add_repository_via_cli(ppa_line, codename, "-y" in args, use_ppas)
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 157, in add_repository_via_cli
    print(" %s" % (ppa_info["description"]))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 353-354: ordinal not in range(128)
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 145, in apport_excepthook
    os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_lib_linuxmint_mintSources_mintSources.py.0.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 1887, in <module>
    add_repository_via_cli(ppa_line, codename, "-y" in args, use_ppas)
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 157, in add_repository_via_cli
    print(" %s" % (ppa_info["description"]))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 353-354: ordinal not in range(128)

```

**Comment by xenopeek** [comment] 2020-01-12 20:59
Couldn't reproduce on Linux Mint 19.3 so I assume this issue has been fixed and as such closing it. You can reopen this if it still happens for you on Linux Mint 19.3.

I added the repository using sudo:
```
$ sudo add-apt-repository -y ppa:jon-hedgerows/get-iplayer
You are about to add the following PPA:
 get_iplayer lists, searches and records BBC iPlayer TV and Radio programmes.

This PPA contains builds of get_iplayer from the master branch at https://github.com/get-iplayer/get_iplayer/, together with sufficiently recent backported builds of AtomicParsley and ffmpeg (for trusty and xenial only).

If the software in this PPA breaks your system, try
  sudo ppa-purge ppa:jon-hedgerows/get-iplayer

For help please read the fine manuals at:
  https://github.com/get-iplayer/get_iplayer/wiki
and use the forums:
  https://squarepenguin.co.uk/

Enjoy!
 More info: https://launchpad.net/~jon-hedgerows/+archive/ubuntu/get-iplayer
Executing: /tmp/apt-key-gpghome.Rwh1Wx2kPY/gpg.1.sh --keyserver hkps://keyserver.ubuntu.com:443 --recv-keys F79D67D8EE8836721D1440E82CDAFB4702E04F78
gpg: key 2CDAFB4702E04F78: public key "Launchpad xbmc" imported
gpg: Total number processed: 1
gpg:               imported: 1
```
I installed get-iplayer afterwards without problems and it shows as installed from the PPA:
```
$ apt policy get-iplayer
get-iplayer:
  Installed: 3.24-ppa33g~bionic
  Candidate: 3.24-ppa33g~bionic
  Version table:
 *** 3.24-ppa33g~bionic 500
        500 http://ppa.launchpad.net/jon-hedgerows/get-iplayer/ubuntu bionic/main amd64 Packages
        500 http://ppa.launchpad.net/jon-hedgerows/get-iplayer/ubuntu bionic/main i386 Packages
        100 /var/lib/dpkg/status
```

**Closed by xenopeek** 2020-01-12 20:59 UTC
