### ISSUE TITLE
Feature requests: two small suggestions for the UI

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/mintsources#167] opened 2019-03-27 08:08 UTC
When adding a repository there is sometimes a delay of up to some ten seconds, as indeed there can be on the command line. Have Software Sources give some indication that something is happening - a busy pointer, a message - seems a good idea.

When one goes to add a repository, one sees the text: 'ppa:username/ppa'. Tthis made me think all entries must end with the string 'ppa'. I know one sees a instruction that says, 'Please enter the name of the PPA you want to add' but, still, I think things could be made clearer. Perhaps the solution would be to add make the instruction line (the 'please enter' line) this: 'Please enter the PPA you wish to add, in the format shown below'. That would make things slightly clearer.

I'm just trying to keep Mint friendly!

**Comment by gm10** [comment] 2019-03-27 08:50
Point of order: Please create a separate issue for each suggestion, that would also allow you to use a descriptive subject line, which makes the whole thing more manageable. 

That said, your #1 should be a non-issue because https://github.com/linuxmint/mintsources/pull/157 should remove the delay (although I generally agree that we need to be more consistent with the busy cursor usage, I already added it in some places), and your #2 will be addressed by https://github.com/linuxmint/mintsources/pull/166.

That's assuming both pull requests end up going in, but I see no reason why they wouldn't.

**Comment by xenopeek** [comment] 2020-05-24 09:00
The second part has been implemented as mentioned above: either the PPA name or the PPA URL can be used to add a PPA through Software Sources. E.g., for adding VLC Daily Build PPA you can either use the name **ppa:videolan/master-daily** as noted on the PPA page or use the URL https://launchpad.net/~videolan/+archive/ubuntu/master-daily.

For the first part I can't reproduce adding a PPA causing a long delay. That may have been improved in mintsources for LM19.2 or for LM19.3. If this is still an issue can you add an example PPA for which you have that problem.

**Closed by xenopeek** 2020-05-24 09:00 UTC
