### ISSUE TITLE
Lots of unreachable servers (LMDE 2)

### ISSUE THREAD

**Issue by riksoft** [linuxmint/mintsources#98] opened 2017-09-09 09:15 UTC
Mint LMDE 2 (betsy) 32 bit.
When I try to select another mirror, mintSources.py starts testing the speed and 50% of the servers are unreachable. e.g. ftp.ticklers.org/debian, or free.hands.com/debian and many others.
However:
- in the browser they work.
- they also work if I select them despite marked as unreachable.

So, there is a problem in the way mintSources.py checks the speed.

In this very moment, I notice there are double named servers in the mirrors list because they have both ftp and http protocol.
http://ftp.ticklers.org is going at 5.5MB/s
while
ftp://ftp.ticklers.org is unreachable.

Maybe the way mintSources test the speed doesn't work with ftp:// ?

**Comment by xenopeek** [comment] 2018-01-29 17:06
I tested it by letting it finish till the end and it looks like (guesstimating) half of the ftp:// mirrors were unreachable for me. Of the http:// mirrors it's more like one in ten that was unreachable.

I notice that for domains that have both a ftp:// and http:// link on the mirror list, the ftp:// link shows as unreachable often. There are exceptions both ways to this though, so it's not as clear cut as that. Results are not consistent either. If I redo the test a little later (sorting on URL and just comparing the first page of results) I see some that were reachable before are now unreachable and vice versa.

This requires more analysis.

**Comment by PaulXiCao** [comment] 2018-04-27 21:00
My setup: Linux Mint 18.3, mintsources 1.7.2

Only 2 servers were marked unreachable (1x ftp, 1x http) and pinging those servers did not work as well.
Thus, I can't reproduce this effect..

**Comment by riksoft** [comment] 2018-04-30 14:49
My bug report is not about Mint, never had problems with Mint, is about Mint LMDE. And by the way almost a year has passed so I can't say if the problem is still there. I'll recheck as soon as possible.

**Comment by riksoft** [comment] 2018-05-02 13:48
Yesterday I tested again my LMDE and the problem was still there on tons of ftp:// mirrors.

**Comment by clefebvre** [comment] 2018-08-09 15:49
Can you reproduce the issue with LMDE 3?

**Comment by riksoft** [comment] 2018-08-10 07:40
I can't tell because I haven't any LMDE 3 installed.

**Comment by pcre** [comment] 2018-09-14 05:37
Hi,

I'm experiencing something similar on Tara with Mate. I think a possible cause can be the polkit or that polkit was not considered. As far as I've read polkit doesn't forward environment variables. If you start mintsources in a terminal with sudo -i or directly as root, my /etc/profile.d/ proxy environment variables are set and all mirrors are reachable.
By the way, It takes too long to find out that the mirrors are unreachable. The window "Select a mirror", where you can see that they are unreachable, takes minutes to open.

Greetings from a newbie,
Peter

**Comment by icarter09** [comment] 2019-12-17 03:02
Anyone have any updates concerning this issue?

**Comment by riksoft** [comment] 2019-12-17 07:50
In the end I solved the issue changing the repos to Debian, complete upgrade and cleaning, migrating from LMDE2 to Debian Buster with zero problems.

**Comment by icarter09** [comment] 2019-12-17 14:53
@riksoft can this ticket be closed?

**Comment by riksoft** [comment] 2019-12-17 19:31
On my part yes, but I have no idea if the bug has been resolved.

**Comment by xenopeek** [comment] 2020-01-13 16:09
I retested this on LMDE 3. Main mirrors come from mint-mirrors package in the Cindy repository; base mirrors come from python-apt-common package in the Stretch repository. For both I find unreachable mirrors and when opened in the web browser most of those that were unreachable also can't be connected to (server not found error or timeout).

For the main mirrors with server not found errors I've asked Clem to remove them from our mirrors list.

I don't know where to report broker mirrors to Debian. These mirrors from Stretch's python-apt-common package all give me server not found errors or timeouts in web browser:
```
http://debian.blizoo.mk/debian
http://debian.e4a.it/debian
http://debian.fastbull.org/debian
http://debian.mirror.lhisp.com/debian
http://debian.mirrors.crysys.hu/debian
http://debian.revolsys.fr/debian
http://ftp.availo.se/debian
http://ftp.gul.uc3m.es/debian
http://ftp.lug.ro/debian
http://ftp.piotrkosoft.net/debian
http://gd.tuwien.ac.at/opsys/linux/debian
http://mirror.atomki.mta.hu/debian
http://mirror.lserg.ru/debian
http://mirror.lwlcom.net/debian
http://mirror.satellite-service.ru/debian
http://mirrors.noction.com/debian/debian
http://mirrors.telianet.dk/debian
```
I don't think this is a mintsources bug; it's an issue with the mirrors list. Closing it for now.

If anybody has the same symptoms I suggest to open a new issue for that. If you do, please start `mintsources` from the terminal, click the main and/or base mirrors to have mintsources speeds test all the mirrors and then copy the output from the terminal and share it here: that shows all the mirrors that mintsources failed to connect to and why they failed.

**Closed by xenopeek** 2020-01-13 16:09 UTC
